services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - PORT=8080
      - QUEUE_URL=amqp://rabbitmq
    volumes:
      - .:/app
  rabbitmq:
       image: rabbitmq:3.13-management
       container_name: rabbitmq
       ports:
         - '5672:5672'
         - '15672:15672'
    

