version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8999:8080'
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
